sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - mkdir wkhtmltopdf
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz -C wkhtmltopdf
  - mv wkhtmltopdf/wkhtmltox wkhtmltopdf/wkhtmltopdf
  - export PATH=$PATH:$PWD/wkhtmltopdf/wkhtmltopdf/bin
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --include=molo.yourtips ^yourtips/ --include=likes ^likes/
  - mkdir -p testapp/testapp/templates/core/tags/
  - cp test_settings.py testapp/testapp/settings/local.py
  - cp molo/yourtips/test_templates/section_page.html testapp/testapp/templates/core/section_page.html
  - cp molo/yourtips/test_templates/section_listing_homepage.html testapp/testapp/templates/core/tags/section_listing_homepage.html
  - flake8 testapp
  - testapp/./manage.py compress --settings=testapp.settings.production --force
  - pip install -e testapp
  - py.test --cov=molo --cov-config .coveragerc
after_success:
  - coveralls
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: hB9qL0xN4Ie7SfzGXqjUa/wMLGrsuAskhwFUCcLaNUqDXzORbC4jSTN64WEGqbrxjz969Y0Fo1D8zj2BncrWQtuA7ApbGhHAIIjA6cY3iEltguv6dZ3u8wCnLicYj1Ahj2xOQaJ2CEeW1yW7o7jtSRHH3U7MuDbY78NwxAufCOFyPMSsea7nRyz/P5qZtj9jTPZk27p+w99snNy5ajmB/XR8bDkEeIJo5RdIOqHvIYqe0IF5W8kTz7DDX1Rb+ictddMYIcr7nTjm/Pljr7w2q1Thbu3FPS2foo9hOTlwMOwzisHOAkBQnshU4E5c/5+SLCh8LFDCLeP3ktD3QEiOStukaoi2rtrt+0Hg+s87h0b6/xhoy/1UGxkendWerBCGONLYe/lt/w0hdzVAMUu6IC6s3owp1HEzrSefcuabRyDh7Ianh63TPvn39SXJOC3iUOVz3HadR2zeJsEWdA6qXdVwHPLe9Udi56ec4E1Mpt4jTDRSmUJHIvCA/ksd0gdMOwCMKd6a7+figtEDX8ylWt6PNWH68Rbm8q+sIFRBipY1TSZqgpeWOl9XLkCo4oYucB+J9GP3flVWLJ+cYFdnCgix8QFIFPaS3YBSS1KVGwk6D5ZUbdgHK9lx8NM1yZrY/2+Ft1aCMYpXN86530TnUOkBRWqu+JITPLpbBnohYQE=
  on:
    tags: true
    all_branches: true
