sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --include molo.yourtips ^yourtips/
  - mkdir -p testapp/testapp/templates/core/tags/
  - cp test_settings.py testapp/testapp/settings/local.py
  - cp molo/yourwords/test_templates/section_page.html testapp/testapp/templates/core/section_page.html
  - cp molo/yourwords/test_templates/section_listing_homepage.html testapp/testapp/templates/core/tags/section_listing_homepage.html
  - flake8 testapp
  - testapp/./manage.py compress --settings=testapp.settings.production --force
  - pip install -e testapp
  - py.test --cov=molo
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: yKvb1/9npBfxxoQmC2zWIs/x9+pijzNo1cQ9pRzEu2wRaJN9Dcg3K06lYE6OzqyTdrQibW49IKPL5MqM2V+lwwYmNBK9V6oJlxLgrvEYoMGr2FlBIVFDMa6aBVH+0d/D9Lpg1pgwDu6ZEsKuQ366uEJcWcc4gAHzELYGmKdXBJksI7IZRbfC1YDbnEymKpAVjxK/sl58sLvLDWqDMrDxTybfw3V4TvOkobFgqTgOSemNegpQBqOXCoXCRwSPK1XgSIGvN3/IiHIruIs9Q41w0KI/364RZ6QQp3tL2vVarguoiV31pQhghwAfVepgBPS1KN63zUgHeisFWAiTYs0RepV9xiPpepGk78TroPrQCpfl+Aorn0fyQAorPKuv/w+chhFcqOfq7ud1ShOnyvPldQk+Kv79H6pn2vVe0u9szLCFuNpxVMCBC54dOKv7vaA0EZwE3cmV7uAFRYEVbWnBS7z6v+Z6VAu37SPIznmFUtdYBOQnKRzTwqmB4bHt0bxqzTdfOAsrhI7WmnoY0Heo0Mk2gGIAAfgrZT4bA4OHPRDEyHdDl/6A27MfqVFKku2DULnuv3lGAmsv0v0p48hhC9Th+FHRrwElAZJ2JJor0lcS6rpccFeS5EmIsUY4nnjS0CtjF6ZjAhi18E2vGlulT8ff/3JJ3ABUzgewtG4IFtA=
  on:
    tags: true
    all_branches: true
