# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-12 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import molo.core.blocks
import molo.core.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('core', '0061_add_success_fields_to_reaction_choice'),
        ('wagtailimages', '0018_remove_rendition_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourTips',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField(blank=True, null=True)),
                ('content', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', molo.core.blocks.MarkDownBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label=b'Item'))), (b'numbered_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label=b'Item'))), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True, null=True)),
                ('extra_style_hints', models.TextField(blank=True, default=b'', help_text='Styling options that can be applied to this section and all its descendants', null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'YourTip',
                'verbose_name_plural': 'YourTips',
            },
            bases=(molo.core.models.TranslatablePageMixinNotRoutable, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='YourTipsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, null=True)),
                ('tip_name', models.CharField(max_length=128)),
                ('tip_text', models.CharField(max_length=140)),
                ('terms_or_conditions_approved', models.BooleanField()),
                ('hide_real_name', models.BooleanField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_shortlisted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'YourTips Entry',
                'verbose_name_plural': 'YourTips Entries',
            },
        ),
        migrations.CreateModel(
            name='YourTipsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', molo.core.models.PreventDeleteMixin),
        ),
        migrations.CreateModel(
            name='YourTipsTermsAndConditions',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.articlepage',),
        ),
        migrations.CreateModel(
            name='YourTipsThankYou',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.articlepage',),
        ),
        migrations.AddField(
            model_name='yourtipsentry',
            name='converted_article_page',
            field=models.ForeignKey(blank=True, help_text='Page to which the entry was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ArticlePage'),
        ),
        migrations.AddField(
            model_name='yourtipsentry',
            name='related_article_page',
            field=models.ForeignKey(blank=True, help_text='Page to which the entry was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ArticlePage'),
        ),
        migrations.AddField(
            model_name='yourtipsentry',
            name='tip_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourtips.YourTips'),
        ),
        migrations.AddField(
            model_name='yourtipsentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
