# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-13 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0002_create_your_tips_index_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourtipsentry',
            name='tip_page',
        ),
    ]
