# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0002_create_index_tip_page'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='yourtipsentrypage',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='yourtipspage',
            name='homepage_action_copy',
            field=models.CharField(default=b'Do you have advice you can share with other youth on relationships?', max_length=255),
        ),
    ]
