# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0003_add_homepage_action_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourtipsarticlepage',
            name='number_of_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
