# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0003_remove_yourtipsentry_tip_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourtipsentry',
            name='converted_article_page',
            field=models.ForeignKey(blank=True, help_text='Article page to which the entry was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ArticlePage'),
        ),
        migrations.AlterField(
            model_name='yourtipsentry',
            name='hide_real_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yourtipsentry',
            name='related_article_page',
            field=models.ForeignKey(blank=True, help_text='Article page related to this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ArticlePage'),
        ),
    ]
