# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-22 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0004_auto_20170620_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourtipsentry',
            name='hide_real_name',
        ),
        migrations.RemoveField(
            model_name='yourtipsentry',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='yourtipsentry',
            name='is_shortlisted',
        ),
        migrations.RemoveField(
            model_name='yourtipsentry',
            name='related_article_page',
        ),
        migrations.RemoveField(
            model_name='yourtipsentry',
            name='tip_name',
        ),
        migrations.AddField(
            model_name='yourtipsentry',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yourtipsentry',
            name='converted_article_page',
            field=models.ForeignKey(blank=True, help_text='Article page to which the entry was converted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tip_entry', to='core.ArticlePage'),
        ),
        migrations.AlterField(
            model_name='yourtipsentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
