# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourtips', '0004_auto_20170706_1256'),
        ('yourtips', '0003_auto_20170705_1011'),
    ]

    operations = [
    ]
