# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_increase_char_length_reaction_success'),
        ('yourtips', '0005_auto_20170623_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourTipsRecentTipsPage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.articlepage',),
        ),
        migrations.RenameModel(
            old_name='YourTips',
            new_name='YourTipsPage',
        ),
        migrations.RenameModel(
            old_name='YourTipsThankYou',
            new_name='YourTipsThankYouPage',
        ),
    ]
